# Generated by Django 4.1.2 on 2022-10-13 04:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ECGScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.upload_to
                    ),
                ),
                ("data", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
